
services:
  server:
    build:
      context: .
    env_file:
      - ./.env
    ports:
      - "${APP_PORT:-9000}:9000"
    restart: always
    volumes:
      - ./model:/mnt/model
      - ./router:/mnt/router
      - ./util:/mnt/util
      - ./alembic:/mnt/alembic
      - ./app.py:/mnt/app.py
      - ./secret:/mnt/secret
      - ./consumer:/mnt/consumer
      - ./web_socket:/mnt/web_socket
    environment:
      SERVICE_NAME: "tongla-hub-server"

  socket-server:
    build:
      context: .
    env_file:
      - ./.env
    ports:
      - "${SOCKET_PORT:-9001}:9001"
    restart: always
    volumes:
      - ./model:/mnt/model
      - ./router:/mnt/router
      - ./util:/mnt/util
      - ./alembic:/mnt/alembic
      - ./app.py:/mnt/app.py
      - ./secret:/mnt/secret
      - ./consumer:/mnt/consumer
      - ./web_socket:/mnt/web_socket
    environment:
      SERVICE_NAME: "tongla-hub-socket-server"

  consumer:
    build:
      context: .
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./model:/mnt/model
      - ./router:/mnt/router
      - ./util:/mnt/util
      - ./alembic:/mnt/alembic
      - ./app.py:/mnt/app.py
      - ./secret:/mnt/secret
      - ./consumer:/mnt/consumer
      - ./web_socket:/mnt/web_socket
    environment:
      SERVICE_NAME: "tongla-hub-consumer"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    env_file:
      - ./.env
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    driver: bridge
