
services:
  mysql:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "tongla-hub"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root

  server:
    build:
      context: .
    env_file:
      - ./.env
    ports:
      - "${APP_PORT:-9000}:9000"
    restart: always
    volumes:
      - ./model:/mnt/model
      - ./router:/mnt/router
      - ./util:/mnt/util
      - ./alembic:/mnt/alembic
      - ./app.py:/mnt/app.py
      - ./secret:/mnt/secret
      - ./consumer:/mnt/consumer
    environment:
      SERVICE_NAME: "tongla-hub-server"

  consumer:
    build:
      context: .
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./model:/mnt/model
      - ./router:/mnt/router
      - ./util:/mnt/util
      - ./alembic:/mnt/alembic
      - ./app.py:/mnt/app.py
      - ./secret:/mnt/secret
      - ./consumer:/mnt/consumer
    environment:
      SERVICE_NAME: "tongla-hub-consumer"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    env_file:
      - ./.env
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql-data:

networks:
  default:
    driver: bridge
