
services:
  base:
    build:
      context: .
    image: tongla-hub:latest
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./model:/mnt/model
      - ./router:/mnt/router
      - ./util:/mnt/util
      - ./alembic:/mnt/alembic
      - ./app.py:/mnt/app.py
      - ./secret:/mnt/secret
      - ./consumer:/mnt/consumer
      - ./web_socket:/mnt/web_socket
      - ./secret/database.pem:/etc/ssl/certs/database.pem:ro
    environment:
      SERVICE_NAME: "tongla-hub-image-base"
    entrypoint: [ "sleep", "infinity" ]
    networks:
      - shared-db

  server:
    image: tongla-hub:latest
    env_file:
      - ./.env
    ports:
      - "${APP_PORT:-9000}:9000"
    restart: always
    volumes:
      - ./model:/mnt/model
      - ./router:/mnt/router
      - ./util:/mnt/util
      - ./alembic:/mnt/alembic
      - ./app.py:/mnt/app.py
      - ./secret:/mnt/secret
      - ./consumer:/mnt/consumer
      - ./web_socket:/mnt/web_socket
      - ./secret/database.pem:/etc/ssl/certs/database.pem:ro
    environment:
      SERVICE_NAME: "tongla-hub-server"
    networks:
      - shared-db

  socket-server:
    image: tongla-hub:latest
    env_file:
      - ./.env
    ports:
      - "${SOCKET_PORT:-9001}:9001"
    restart: always
    volumes:
      - ./model:/mnt/model
      - ./router:/mnt/router
      - ./util:/mnt/util
      - ./alembic:/mnt/alembic
      - ./app.py:/mnt/app.py
      - ./secret:/mnt/secret
      - ./consumer:/mnt/consumer
      - ./web_socket:/mnt/web_socket
      - ./secret/database.pem:/etc/ssl/certs/database.pem:ro
    environment:
      SERVICE_NAME: "tongla-hub-socket-server"
    networks:
      - shared-db

  cron-job:
    image: tongla-hub:latest
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./model:/mnt/model
      - ./router:/mnt/router
      - ./util:/mnt/util
      - ./alembic:/mnt/alembic
      - ./app.py:/mnt/app.py
      - ./secret:/mnt/secret
      - ./consumer:/mnt/consumer
      - ./web_socket:/mnt/web_socket
      - ./secret/database.pem:/etc/ssl/certs/database.pem:ro
    environment:
      SERVICE_NAME: "tongla-hub-cron"
    networks:
      - shared-db

  consumer:
    image: tongla-hub:latest
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./model:/mnt/model
      - ./router:/mnt/router
      - ./util:/mnt/util
      - ./alembic:/mnt/alembic
      - ./app.py:/mnt/app.py
      - ./secret:/mnt/secret
      - ./consumer:/mnt/consumer
      - ./web_socket:/mnt/web_socket
      - ./secret/database.pem:/etc/ssl/certs/database.pem:ro
    environment:
      SERVICE_NAME: "tongla-hub-consumer"
    depends_on:
      - rabbitmq
    networks:
      - shared-db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    env_file:
      - ./.env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - shared-db

networks:
  shared-db:
    external: true
    name: shared-db
