"""migrate-20251901223350

Revision ID: 0e2779c8b44c
Revises: 19d752093c6e
Create Date: 2025-01-19 22:33:51.070275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2779c8b44c'
down_revision: Union[str, None] = '19d752093c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('is_system_question', sa.Boolean(), nullable=True))
    op.add_column('question', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'is_public')
    op.drop_column('question', 'is_system_question')
    # ### end Alembic commands ###
