"""migrate-20252001160807

Revision ID: 1ce7905075b5
Revises: 0e2779c8b44c
Create Date: 2025-01-20 16:08:07.761281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce7905075b5'
down_revision: Union[str, None] = '0e2779c8b44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answer_code', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'answer_code')
    # ### end Alembic commands ###
