"""migrate-20250102131059

Revision ID: 8d840a717cbe
Revises: 0bbc8984a0e1
Create Date: 2025-02-01 13:10:59.831440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d840a717cbe'
down_revision: Union[str, None] = '0bbc8984a0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submit', sa.Column('info', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submit', 'info')
    # ### end Alembic commands ###
